### ISSUE TITLE
Python 2.6 not compatible : test failures

### ISSUE THREAD

**Issue by frallain** [tomerfiliba/minima#1]
Python version used : Python 2.6.6 (r266:84297, Aug 24 2010, 18:46:32) [MSC v.1500 32 bit (Intel)] on win32

```
**********************************************************************
File "hypertext.py", line 55, in __main__
Failed example:
    with div.content as root:
        with h1:
            ATTR(class_ = "highlight")
            TEXT("hello")
Exception raised:
    Traceback (most recent call last):
      File "C:\Python26\lib\doctest.py", line 1253, in __run
        compileflags, 1) in test.globs
      File "<doctest __main__[11]>", line 2, in <module>
        with h1:
    TypeError: unbound method __enter__() must be called with h1 instance as first argument (got nothing instead)
**********************************************************************
File "hypertext.py", line 60, in __main__
Failed example:
    print root
Expected:
    <div class="content"><h1 class="highlight">hello</h1></div>
Got:
    <div class="content"/>
**********************************************************************
File "hypertext.py", line 78, in __main__
Failed example:
    with html as doc:                                    # doctest:+ELLIPSIS
        with head:
            meta(http_equiv="Content-Type", content="text/html; charset=utf-8")
            title("welcome to my page")
        with body:
            ATTR(id="body")
            with div.content(id = "floop", data_role = "page").pretty:
                TEXT("Hello, my <name> is")
                strong("Bob")
                TEXT("Also known as", em("Robert"))
                UNESCAPED("and I <b>like</b>")
                with ul:
                    for item in ["cats", "rats", "hats"]:
                        li(item)
Exception raised:
    Traceback (most recent call last):
      File "C:\Python26\lib\doctest.py", line 1253, in __run
        compileflags, 1) in test.globs
      File "<doctest __main__[15]>", line 1, in <module>
        with html as doc:                                    # doctest:+ELLIPSIS
    TypeError: unbound method __enter__() must be called with html instance as first argument (got nothing instead)
**********************************************************************
File "hypertext.py", line 94, in __main__
Failed example:
    print doc
Exception raised:
    Traceback (most recent call last):
      File "C:\Python26\lib\doctest.py", line 1253, in __run
        compileflags, 1) in test.globs
      File "<doctest __main__[16]>", line 1, in <module>
        print doc
    NameError: name 'doc' is not defined
**********************************************************************
1 items had failures:
   4 of  17 in __main__
***Test Failed*** 4 failures.
```

**Comment by tomerfiliba** [comment]
funny, it seems that prior to python 2.7, `__enter__` and `__exit__` were not real slots and were looked up in the instance instead in its type.

```
>>> class X(object):
...     class __metaclass__(type):
...             def __enter__(self):
...                     return 17
...             def __exit__(self, t, v, tb):
...                     pass
...
>>> X.__enter__
<bound method __metaclass__.__enter__ of <class '__main__.X'>>
>>> X.__enter__()
17
>>> with X:
...     pass
...
>>> class X(object):
...     class __metaclass__(type):
...             def __enter__(self):
...                     return 17
...             def __exit__(self, t, v, tb):
...                     pass
...
...     def __enter__(self):
...             return 18
...     def __exit__(self, t, v, tb):
...             pass
...
>>>
>>> x=X()
>>> with x as foo:
...     print foo
...
18
>>> X.__enter__
<unbound method X.__enter__>
>>> with X:
...     pass
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unbound method __enter__() must be called with X instance as first argument (got nothing instead)
```

**Comment by tomerfiliba** [comment]
please use https://github.com/tomerfiliba/srcgen/blob/master/srcgen/hypertext.py instead
i'm moving all of my code generators to that repo

**Comment by tomerfiliba** [comment]
can you open a ticket on the new repo and link to this one?

**Comment by frallain** [comment]
Done except the link to the old one, I don't know how to do it...

François ALLAIN

06.51.39.99.06
