### ISSUE TITLE
Python 2.6 : multiple context managers

### ISSUE THREAD

**Issue by frallain** [tomerfiliba/minima#2]
Thanks for the fix, it works for one context manager but in the example below (with 2 context managers), I've got this exception :

```
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    with html as root:
  File "C:\Users\l-fa229081.VRH026543\Downloads\python\hypertext\hypertext.py", line 78, in __get__
    return _per_thread.stack[-1].__exit__
IndexError: list index out of range
```

```
from hypertext import *

with div.content as root:
    h1.highlight("Welcome")
    TEXT("This is my page")
print root

with html as root:
    with head:
        meta(http_equiv="Content-Type", content="text/html; charset=utf-8")
        title("welcome to my page")
    with body:
        ATTR(id="body")
        with div.content(id = "floop", data_role = "page").pretty:
            TEXT("Hello, my <name> is")
            strong("Bob")
            TEXT("Also known as", em("Robert"))
            UNESCAPED("and I <b>like</b>")
            with ul:
                for item in ["cats", "rats", "hats"]:
                    li(item)
print root
```

Is it a normal behaviour ?

**Comment by tomerfiliba** [comment]
the new repo is https://github.com/tomerfiliba/srcgen...

**Comment by tomerfiliba** [comment]
fixed in https://github.com/tomerfiliba/srcgen/issues/1
